name: Daily Update and Deployment

on:
  workflow_dispatch:
  # Uncomment to schedule daily runs
  # schedule:
  #   - cron: '0 12 * * *'  # Daily at 5 AM Pacific / 12 PM UTC
  # push:
  #   branches:
  #     - main

permissions:
  contents: write

jobs:
  render_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Debug forecast_results.csv
      - name: Debug forecast_results.csv
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files in inst/data-cache:"
          ls -l inst/data-cache/ || echo "Directory does not exist"
          echo "Contents of forecast_results.csv:"
          cat inst/data-cache/forecast_results.csv || echo "File does not exist"

      # 3. Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libx11-dev libcurl4-openssl-dev libssl-dev make \
            pandoc libfreetype6-dev libjpeg-dev libpng-dev libtiff-dev libicu-dev \
            libfontconfig1-dev libfribidi-dev libharfbuzz-dev libxml2-dev \
            libcairo2-dev zlib1g-dev libnode-dev

      # 4. Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # 5. Cache R packages managed by renv
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: |
            renv/library
            renv/cache
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      # 6. Debug renv folders before install
      - name: Check for renv/library before restore
        run: |
          echo "Checking for renv/library and renv/cache:"
          ls -l renv/ || echo "renv/ does not exist"
          ls -l renv/library || echo "renv/library does not exist"
          ls -l renv/cache || echo "renv/cache does not exist"

      # 7. Install renv and restore environment
      - name: Install and restore renv
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      # 8. (Optional) Check renv status
      - name: Check renv status
        run: renv::status()
        shell: Rscript {0}

      # 9. Install the Inseasonfor package from local source
      - name: Install Inseasonfor from local source
        run: install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      # 10. Render the report using package function
      - name: Render the report
        run: Rscript -e 'Inseasonfor::render_page_fun()'

      # 11. Commit updated CSVs (if changed)
      - name: Commit updated CSV files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "mark.sorel@dfw.wa.gov"
          git config user.name "marksorel8"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/marksorel8/Inseasonfor.git
          git add inst/data-cache/*.csv || true
          git diff --cached --quiet || git commit -m "Update CSV files"
          git push origin main

      # 12. Debug inst directory (optional)
      - name: Debug inst directory
        run: |
          echo "Listing files in inst directory:"
          ls -l inst/

      # Debug site directory before deployment
      - name: Debug site directory
        run: |
          ls -lh site || echo "site/ does not exist"
          ls -lh site/index.html || echo "index.html not found"


      # 13. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
